openapi: 3.2.0
info:
  version: 2.0.0
  title: Anchorage Digital API Reference API Key API
  contact:
    email: api@anchorage.com
  description: '# Introduction

    *CONFIDENTIAL: Please do not distribute this documentation externally without prior Anchorage Digital approval.*


    The Anchorage Digital REST API v2.0 provides a set of operations and resources that allow Anchorage Digital clients and partners to:

    - Programmatically transfer funds from an Anchorage Digital vault or wallet without human intervention

    - Create and list deposit addresses in a vault

    - Read and monitor vault balances

    - Query transaction history including deposits

    …'
servers:
- url: https://api.anchorage-staging.com/v2
security:
- Api-Access-Key: []
tags:
- description: These endpoints allow querying information about the current API key in use.
  name: API Key
paths:
  /apikey:
    get:
      operationId: getAPIKeyInfo
      summary: List information for current API key
      description: 'Permissions required: none


        Get the user information for your API key.


        As with any endpoint, a signature included in the request will be validated. This can be used to confirm the associated signing key as well information about the current API key.'
      parameters: []
      responses:
        '200':
          description: Information for current API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIKeyInfoResponse'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
      tags:
      - API Key
components:
  schemas:
    APIKeyDetails:
      type: object
      properties:
        id:
          description: An ID uniquely identifying an API key.
          type: string
        permissions:
          description: The permissions enabled for an API key. Each permission maps to an object, which may contain additional qualifiers.
          type: array
          items:
            type: object
            required:
            - permission
            properties:
              permission:
                type: string
                enum:
                - AUTHORIZE_SETTLEMENTS
                - CREATE_DEPOSIT_ADDRESS
                - DEPOSIT_ATTRIBUTION
                - EXTERNAL_LOAN_WRITE
                - FACILITY_ONLY
                - INTERNAL_TRANSFER
                - INITIATE_WITHDRAWAL
                - LENDER_READ
                - ONBOARDING
                - WRITE_TAX
                - PROPOSE_ACCEPT_SETTLEMENTS
                - READ
                - READ_DEPOSIT_ATTRIBUTION
                - READ_SUBACCOUNT
                - READ_TRADE
                - SUBACCOUNT
                - TRADE
                - TRANSFER
                - CONVERT_STABLECOINS
                - FIAT_BANKING
                - CONFIGURE_WEBHOOKS
              vaultIds:
                description: The vaultIds for which this permission may be used. VaultIds are not applicable to all permissions.
                type: array
                items:
                  type: string
                uniqueItems: true
                x-omitempty: true
      example:
        id: b5a58566763e77e2d87a53463013981be7c0b048c1c0dd39ba44e77c99bc1351
        permissions:
        - permission: READ
          vaultIds:
          - 1c920f4241b78a1d483a29f3c24b6c4c
          - 55e89d4a644d736b01533a2ea9b32a20
        - permission: TRADE
      required:
      - id
      - permissions
      title: APIKeyDetails
    ErrorType:
      description: The type of error returned.
      type: string
      enum:
      - InternalError
      - InvalidRequest
      - Unauthenticated
      - Forbidden
      - NotFound
      - Conflict
      - UnprocessableEntity
      - TooManyRequests
      - ServiceUnavailable
      - QuoteExpired
      - InsufficientFunds
      - NotImplemented
      title: ErrorType
    APIKeyInfoResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/APIKeyDetails'
      required:
      - data
      title: APIKeyInfoResponse
    ErrorDetails:
      type: object
      properties:
        errorType:
          $ref: '#/components/schemas/ErrorType'
        message:
          description: A human-readable message providing more details about the error.
          type: string
          example: Missing required field 'amount'.
      required:
      - errorType
      - message
      title: ErrorDetails
  securitySchemes:
    Api-Access-Key:
      type: apiKey
      name: Api-Access-Key
      in: header
      description: An API key associated with a security role
x-tagGroups:
- name: Under Development
  tags:
  - Collateral Management
  - Holds
  - Deposit Attribution
  - Onboarding
  - Trusted Destinations
  - Atlas Settlement Network
  - Tax
- name: API Endpoints
  tags:
  - Addresses
  - Asset Types
  - Transactions
  - Transfers
  - Wallets
  - Vaults
  - Vesting
  - Tagging
  - Subaccounts
  - Stablecoins
  - Webhook Notifications
  - API Key
  - Statements
  - Tax Reporting
  - Trading
- name: Models
  tags:
  - Transfer Model
  - Transaction Model
  - Vault Model
  - Deposit Attribution Model
