openapi: 3.2.0
info:
  version: 2.0.0
  title: Anchorage Digital API Reference Vaults API
  contact:
    email: api@anchorage.com
  description: '# Introduction

    *CONFIDENTIAL: Please do not distribute this documentation externally without prior Anchorage Digital approval.*


    The Anchorage Digital REST API v2.0 provides a set of operations and resources that allow Anchorage Digital clients and partners to:

    - Programmatically transfer funds from an Anchorage Digital vault or wallet without human intervention

    - Create and list deposit addresses in a vault

    - Read and monitor vault balances

    - Query transaction history including deposits

    …'
servers:
- url: https://api.anchorage-staging.com/v2
security:
- Api-Access-Key: []
tags:
- description: An Anchorage Digital organization has one or more vaults.
  name: Vaults
paths:
  /vaults:
    get:
      operationId: getVaults
      summary: List vaults
      description: 'Permissions required: **Read vault activity**


        List vault metadata including name, ID, description, and assets.


        NOTE: price and USD value information is recent but does not reflect real-time data.'
      parameters:
      - name: afterId
        in: query
        description: When paginating this is used to provide the starting point for the page to fetch (retrieved from the previous response body)
        schema:
          type: string
      - name: limit
        in: query
        description: Maximum number of results to return per query
        schema:
          type: integer
          format: int64
          default: 25
          maximum: 100
          minimum: 1
      responses:
        '200':
          description: A list of vaults and their metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VaultsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
      tags:
      - Vaults
      x-security:
        Read vault activity: present
  /vaults/{vaultId}:
    get:
      operationId: getVault
      summary: Get vault by ID
      description: 'Permissions required: **Read vault activity**


        Get vault by ID'
      parameters:
      - name: vaultId
        in: path
        description: The ID of the vault to get details for
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A vault's metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VaultsResponse1'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
      tags:
      - Vaults
      x-security:
        Read vault activity: checkSourceVault
components:
  schemas:
    VaultDetails:
      type: object
      properties:
        accountName:
          description: Account name
          type: string
        assets:
          description: A list of the assets in this vault
          type: array
          items:
            $ref: '#/components/schemas/AssetDetails'
        description:
          description: A description of the vault
          type: string
        name:
          description: Vault name
          type: string
        type:
          description: Always VAULT
          type: string
        vaultId:
          description: An ID uniquely identifying an Anchorage Digital vault.
          type: string
          example: 1c920f4241b78a1d483a29f3c24b6c4c
      example:
        vaultId: 1c920f4241b78a1d483a29f3c24b6c4c
        name: Long Hold Vault
        description: For long-term investments
        type: VAULT
        accountName: Account name
        assets:
        - walletId: 3d293c0d64c703023692216e9b4f5280
          assetType: BTC
          availableBalance:
            quantity: '10.00000000'
            assetType: BTC
            currentPrice: '9751.01'
            currentUSDValue: '97510.1'
          totalBalance:
            quantity: '10.45234733'
            assetType: BTC
            currentPrice: '9751.01'
            currentUSDValue: '101920.94'
          stakedBalance:
            quantity: '32.00000000'
            assetType: BTC
            currentPrice: '9751.01'
            currentUSDValue: '312032.32'
          unclaimedBalance:
            quantity: '0'
            assetType: BTC
            currentPrice: '9751.01'
            currentUSDValue: '0'
          vaultId: 1c920f4241b78a1d483a29f3c24b6c4c
          vaultName: Long Hold Vault
      required:
      - vaultId
      - name
      - description
      - assets
      - type
      title: VaultDetails
    VaultsResponse1:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/VaultDetails'
      required:
      - data
      title: VaultsResponse1
    ErrorType:
      description: The type of error returned.
      type: string
      enum:
      - InternalError
      - InvalidRequest
      - Unauthenticated
      - Forbidden
      - NotFound
      - Conflict
      - UnprocessableEntity
      - TooManyRequests
      - ServiceUnavailable
      - QuoteExpired
      - InsufficientFunds
      - NotImplemented
      title: ErrorType
    Page:
      description: Pagination info
      type: object
      properties:
        next:
          description: URL to use to query for the next page or null if no additional results are available
          type:
          - string
          - 'null'
          example: <next page url>
          x-omitempty: false
      title: Page
    AssetDetails:
      type: object
      properties:
        assetType:
          description: 'A string representing a type of crypto-asset, which usually corresponds to the crypto asset''s ticker symbol.


            Use `/asset-types` to list all of the supported asset types for your organization.

            '
          type: string
          example: BTC
        availableBalance:
          $ref: '#/components/schemas/Amount'
        stakedBalance:
          $ref: '#/components/schemas/Amount'
        totalBalance:
          $ref: '#/components/schemas/Amount'
        unclaimedBalance:
          $ref: '#/components/schemas/Amount'
        vaultId:
          description: The unique ID of the vault that this asset is in
          type: string
        vaultName:
          description: The name of the vault that this asset is in
          type: string
        walletId:
          description: An ID uniquely identifying an Anchorage Digital wallet
          type: string
      example:
        walletId: 3d293c0d64c703023692216e9b4f5280
        assetType: BTC
        availableBalance:
          quantity: '10.00000000'
          assetType: BTC
          currentPrice: '9751.01'
          currentUSDValue: '97510.1'
        totalBalance:
          quantity: '10.45234733'
          assetType: BTC
          currentPrice: '9751.01'
          currentUSDValue: '101920.94'
        stakedBalance:
          quantity: '32.00000000'
          assetType: BTC
          currentPrice: '9751.01'
          currentUSDValue: '312032.32'
        unclaimedBalance:
          quantity: '0'
          assetType: BTC
          currentPrice: '9751.01'
          currentUSDValue: '0'
        vaultId: 1c920f4241b78a1d483a29f3c24b6c4c
        vaultName: Long Hold Vault
      required:
      - walletId
      - assetType
      - availableBalance
      - totalBalance
      - vaultId
      - vaultName
      title: AssetDetails
    Amount:
      description: 'An amount of a crypto-asset represented by quantity, assetType, current unit price and current USD value.



        Fee amounts will be estimates if a transaction is not final.



        NOTE: price and USD value information is recent but does not reflect real-time data.

        '
      type: object
      properties:
        assetType:
          description: 'A string representing a type of crypto-asset, which usually corresponds to the crypto asset''s ticker symbol.


            Use `/asset-types` to list all of the supported asset types for your organization.

            '
          type: string
          example: BTC
        currentPrice:
          description: A recent assessment of the intra-day USD value of 1 unit of this asset type. This value is provided for convenience for such use cases as estimating point-in-time portfolio balances. This value does not represent authoritative pricing information used by Anchorage Digital for any purpose. The price is fetched as of the present, and may be omitted in certain contexts where more structured pricing information is provided (e.g. quotes and trades).
          type: string
          example: '9751.01'
        currentUSDValue:
          description: The result of `quantity * currentPrice`, rounded to the nearest cent. A unitless number implicitly denominated in dollars. See `currentPrice` for methodology and disclaimers.
          type: string
          example: '101920.94'
        quantity:
          description: The numeric value of this amount, excluding units
          type: string
          example: '10.45234733'
      example:
        quantity: '10.45234733'
        assetType: BTC
        currentPrice: '9751.01'
        currentUSDValue: '101920.94'
      required:
      - quantity
      - assetType
      title: Amount
    VaultsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/VaultDetails'
        page:
          $ref: '#/components/schemas/Page'
      required:
      - data
      - page
      title: VaultsResponse
    ErrorDetails:
      type: object
      properties:
        errorType:
          $ref: '#/components/schemas/ErrorType'
        message:
          description: A human-readable message providing more details about the error.
          type: string
          example: Missing required field 'amount'.
      required:
      - errorType
      - message
      title: ErrorDetails
  securitySchemes:
    Api-Access-Key:
      type: apiKey
      name: Api-Access-Key
      in: header
      description: An API key associated with a security role
x-tagGroups:
- name: Under Development
  tags:
  - Collateral Management
  - Holds
  - Deposit Attribution
  - Onboarding
  - Trusted Destinations
  - Atlas Settlement Network
  - Tax
- name: API Endpoints
  tags:
  - Addresses
  - Asset Types
  - Transactions
  - Transfers
  - Wallets
  - Vaults
  - Vesting
  - Tagging
  - Subaccounts
  - Stablecoins
  - Webhook Notifications
  - API Key
  - Statements
  - Tax Reporting
  - Trading
- name: Models
  tags:
  - Transfer Model
  - Transaction Model
  - Vault Model
  - Deposit Attribution Model
